Repository prgrms-web-devcourse-final-project/WEB3_4_Log4U_BE, pull requests merged in 2025-04, with the labels that each got.

#23 다이어리 도메인 테스트 추가
  src/main/java/com/example/log4u/domain/comment/entity/Comment.java
  src/main/java/com/example/log4u/domain/diary/controller/DiaryController.java
  src/main/java/com/example/log4u/domain/diary/entity/Diary.java
  src/main/java/com/example/log4u/domain/diary/repository/CustomDiaryRepositoryImpl.java
  src/main/java/com/example/log4u/domain/diary/service/DiaryService.java
  src/main/java/com/example/log4u/domain/media/service/MediaService.java
  src/test/java/com/example/log4u/domain/diary/controller/DiaryControllerTest.java
  src/test/java/com/example/log4u/domain/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/example/log4u/domain/diary/service/DiaryServiceTest.java
  src/test/java/com/example/log4u/fixture/DiaryFixture.java
  src/test/java/com/example/log4u/fixture/MediaFixture.java
Labels: refactor, test

#22 신고/문의 엔티티 리팩토링 및 문의 서비스 단위 테스트 추가
  src/main/java/com/example/log4u/domain/reports/entity/Report.java
  src/main/java/com/example/log4u/domain/supports/controller/SupportController.java
  src/main/java/com/example/log4u/domain/supports/entity/Support.java
  src/main/java/com/example/log4u/domain/supports/repository/SupportQuerydsl.java
  src/main/java/com/example/log4u/domain/supports/service/SupportService.java
  src/test/java/com/example/log4u/domain/support/service/SupportServiceTest.java
Labels: refactor, test

#24 특정 다이어리 댓글 전체 조회(커서 기반) API 구현
  src/main/java/com/example/log4u/domain/comment/controller/CommentController.java
  src/main/java/com/example/log4u/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/example/log4u/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/log4u/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/example/log4u/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/example/log4u/domain/comment/service/CommentService.java
  src/test/java/com/example/log4u/domain/comment/service/CommonServiceTest.java
  src/test/java/com/example/log4u/fixture/CommentFixture.java
Labels: enhancement

#31 지도 범위 내 클러스터형 공개 다이어리 조회 API 구현 (줌레벨 기준 시/도, 시군구 클러스터)
  build.gradle.kts
  docker-compose.yml
  src/main/java/com/example/log4u/common/config/MySqlConfig.java
  src/main/java/com/example/log4u/common/config/PostgreSqlConfig.java
  src/main/java/com/example/log4u/common/config/PostgresQuerydslConfig.java
  src/main/java/com/example/log4u/common/config/QueryDslConfig.java
  src/main/java/com/example/log4u/domain/diary/service/DiaryService.java
  src/main/java/com/example/log4u/domain/map/controller/MapController.java
  src/main/java/com/example/log4u/domain/map/dto/response/DiaryClusterResponseDto.java
  src/main/java/com/example/log4u/domain/map/entity/SidoAreas.java
  src/main/java/com/example/log4u/domain/map/entity/SidoAreasDiaryCount.java
  src/main/java/com/example/log4u/domain/map/entity/SidoCodeMap.java
  src/main/java/com/example/log4u/domain/map/entity/SiggAreas.java
  src/main/java/com/example/log4u/domain/map/entity/SiggAreasDiaryCount.java
  src/main/java/com/example/log4u/domain/map/exception/MapErrorCode.java
  src/main/java/com/example/log4u/domain/map/exception/MapException.java
  src/main/java/com/example/log4u/domain/map/exception/NotFoundRegionException.java
  src/main/java/com/example/log4u/domain/map/repository/SidoAreasDiaryCountRepository.java
  src/main/java/com/example/log4u/domain/map/repository/SidoAreasRepository.java
  src/main/java/com/example/log4u/domain/map/repository/SidoAreasRepositoryCustom.java
  src/main/java/com/example/log4u/domain/map/repository/SidoAreasRepositoryImpl.java
  src/main/java/com/example/log4u/domain/map/repository/SiggAreasDiaryCountRepository.java
  src/main/java/com/example/log4u/domain/map/repository/SiggAreasRepository.java
  src/main/java/com/example/log4u/domain/map/repository/SiggAreasRepositoryCustom.java
  src/main/java/com/example/log4u/domain/map/repository/SiggAreasRepositoryImpl.java
  src/main/java/com/example/log4u/domain/map/service/MapService.java
  src/test/java/com/example/log4u/domain/Map/service/MapServiceTest.java
  src/test/java/com/example/log4u/domain/diary/repository/DiaryRepositoryTest.java
  src/test/java/com/example/log4u/domain/diary/service/DiaryServiceTest.java
  src/test/java/com/example/log4u/domain/follow/FollowTest.java
  src/test/java/com/example/log4u/fixture/AreaClusterFixture.java
Labels: enhancement

#39 특정 다이어리 댓글 전체 조회 API 반환 데이터 수정
  src/main/java/com/example/log4u/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/example/log4u/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/example/log4u/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/example/log4u/domain/comment/service/CommentService.java
  src/test/java/com/example/log4u/domain/comment/service/CommonServiceTest.java
  src/test/java/com/example/log4u/fixture/CommentFixture.java
Labels: refactor

#49 다이어리 수정·삭제 시 지역별 다이어리 개수 갱신 로직 추가
  src/main/java/com/example/log4u/domain/diary/facade/DiaryFacade.java
  src/main/java/com/example/log4u/domain/map/entity/SidoAreasDiaryCount.java
  src/main/java/com/example/log4u/domain/map/entity/SiggAreasDiaryCount.java
  src/main/java/com/example/log4u/domain/map/service/MapService.java
Labels: refactor

#48 성능 테스트 환경 구축 및 API 성능 분석 (k6, Prometheus, Grafana)
  Dockerfile
  build.gradle.kts
  docker-compose.perf.yml
  performance-test.js
  prometheus.yml
  src/main/java/com/example/log4u/common/config/MySqlConfig.java
  src/main/java/com/example/log4u/common/oauth2/jwt/JwtAuthenticationFilter.java
  src/test/java/com/example/log4u/domain/media/repository/MediaRepositoryTest.java
Labels: enhancement
